### ISSUE TITLE
Create a "scripts" folder at the root of the repository (next to the top-level "spicy-of" folder)

### ISSUE THREAD

**Issue by Kraft-Dinner** [Kraft-Dinner/spicy-of#1]
### Objective

We want to have a "scripts" folder alongside the top-level "spicy-of" folder to hold our one-off loose scripts that aren't directly related to the app code.

So with this work the repository directory tree should look like:
```
spicy-of/
   - app/
   - public/
   - {bunch of files}
 scripts/
README.md
```

Once the new folder has been created we will need to the be committed to the repository and pushed to the remote repo.

### Learning topics
Github repository basics (cloning repository, adding new folder, staging changes, commit changes, push to remote): https://docs.github.com/en/get-started/using-git/about-git

**Comment by MouthfulOfWocc** [comment]
boss said good, i hit buttons
